=== growing-web/cli/packages/schema/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://growing-web.manifest/schema.json",
  "title": "Project Manifest",
  "description": "Project list field in growing-web.",
  "type": "object",
  "additionalProperties": false,
  "definitions": {
    "entry": { "type": "string" },
    "publicPath": { "type": "string" },
    "outDir": { "type": "string" },
    "externals": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        "[a-zA-Z]+": {
          "anyOf": [{ "type": "string" }, { "type": "null" }]
        }
      }
    },

    "server": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "port": { "type": "number", "minimum": 0, "maximum": 65535 },
        "proxy": { "$ref": "#/definitions/proxy" },
        "host": { "type": "string" }
      }
    },
    "formats": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["cjs", "esm", "iife", "umd", "system"]
      }
    },
    "importmap": {
      "anyOf": [{ "type": "string" }, { "type": "null" }]
    },
    "proxy": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "url": { "type": "string" },
          "target": { "type": "string" },
          "secure": { "type": "boolean" },
          "changeOrigin": { "type": "boolean" },
          "pathRewrite": {
            "$ref": "#/definitions/pathRewrite"
          }
        },
        "required": ["url", "target"]
      }
    },
    "pathRewrite": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "regular": {
            "anyOf": [{ "instanceof": "RegExp" }, { "type": "string" }]
          },
          "replacement": {
            "type": "string"
          }
        }
      }
    }
  },
  "properties": {
    "$schema": {
      "description": "schema remote path.",
      "type": "string"
    },
    "schemaVersion": {
      "description": "The version number of the manifest.",
      "type": "string"
    },
    "entry": {
      "$ref": "#/definitions/entry",
      "description": "application entry file."
    },
    "publicPath": {
      "$ref": "#/definitions/publicPath",
      "description": "Build tools publicPath configuration."
    },
    "externals": {
      "$ref": "#/definitions/externals",
      "description": "Shared Dependencies & Common Dependencies."
    },
    "outDir": {
      "$ref": "#/definitions/outDir",
      "description": "Build product output directory."
    },
    "importmap": {
      "$ref": "#/definitions/importmap",
      "description": "generate importmap."
    },
    "formats": {
      "$ref": "#/definitions/formats",
      "description": "build product formats."
    },
    "server": {
      "$ref": "#/definitions/server",
      "description": "local server configuration"
    },
    "env": {
      "type": "object",
      "description": "env configuration for different environments.",
      "additionalProperties": false,
      "patternProperties": {
        "[a-z]+": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "entry": { "$ref": "#/definitions/entry" },
            "publicPath": { "$ref": "#/definitions/publicPath" },
            "externals": { "$ref": "#/definitions/externals" },
            "outDir": { "$ref": "#/definitions/outDir" },
            "importmap": { "$ref": "#/definitions/importmap" },
            "formats": { "$ref": "#/definitions/formats" },
            "server": {
              "$ref": "#/definitions/server"
            }
          }
        }
      }
    }
  },
  "required": ["schemaVersion", "entry"]
}

=== growing-web/cli/playgrounds/vue2/project-manifest.json
{
  "schemaVersion": "0.0.0",
  "entry": "index.html",
  "publicPath": "/",
  "externals": {},
  "server": {
    "proxy": [
      {
        "url": "/api",
        "target": "http://localhost:3000/api?a=1&b=1",
        "pathRewrite": [
          {
            "regular": "^/api",
            "replacement": ""
          }
        ]
      }
    ]
  }
}
